### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by K3NOXOFFICIAL** [Ashanime/Ashanime-Web-App#9]
# To-Do List

- **GitHub Project:**

- **Bug Fixes:**

  

- **Feature Requests:**

  
   - [ ] Add Airing schedule
   - [ ] Dropdown Menu to Sort The Watchlist by Recently Updated or Recently Watched
   - [ ] Series release order
   - [ ] Add Comments section (@K3NOXOFFICIAL)
   - [ ] Add Some uncensored Anime 
   - [ ] Add Manga
   - [ ] My Anime List Support (@K3NOXOFFICIAL)
   - [ ] Auto Play Next Episode 

- # Fixed / Added

   -  Fix the Watchlist not showing when reloading. (@K3NOXOFFICIAL)
   -  Fix Some Animes not able to add to Watchlist (@K3NOXOFFICIAL)
   -  Wrong Anime showing when using Crunchyroll or Animefox (@K3NOXOFFICIAL)
   -  Anime Dub not working (@K3NOXOFFICIAL)
   -  Watchlist Title cut off   (@K3NOXOFFICIAL)
   -  Finish Axios Refactor  (@ahmedalashhab)
   -  Types should be PascalCase   (@ahmedalashhab)
   -  Import Notifications  (@K3NOXOFFICIAL)
   -  Fix Auto Rotate (@K3NOXOFFICIAL)
   -  Fix Cors Error (@K3NOXOFFICIAL)
   -  Clean up ReadMe   (@K3NOXOFFICIAL)
   -  Set Up Wiki Pages  (@K3NOXOFFICIAL)
   -  Set Up Issue Templates   (@K3NOXOFFICIAL)
   -  Add Project to Index.moe     **([Yanki](https://discord.com/users/Yanki#0202))**
   -  Create To-Do List   (@K3NOXOFFICIAL)
   -  Easy Deploy  (@K3NOXOFFICIAL)
   -  Continue Watching Page (@ahmedalashhab)
   -  A button For skipping the Intro (@ahmedalashhab)
   -  Watch it again on main Page (@K3NOXOFFICIAL)
   -  Desktop and App Notifications for new episodes  (@K3NOXOFFICIAL)
   -  Add Notification Frame  (@K3NOXOFFICIAL)
   -  Firebase Config Notifications  (@K3NOXOFFICIAL)
   -  Terms Of Service Page  (@K3NOXOFFICIAL)
   -  Caching For the main Site and Artwork so it doesn't Load for Ages. (@K3NOXOFFICIAL)
   -  #24 (@ahmedalashhab)  
   -  New API Implementation (@K3NOXOFFICIAL)
   -  Skipping all Intros automatically (@K3NOXOFFICIAL)
   -  Automatically Choose Dub instead of Sub (@K3NOXOFFICIAL)
   - Auto Provider (Always choose fastest Provider) (@K3NOXOFFICIAL)
   - Self Hosted Account Database
   - More Sources for More Dub Languages (Like Crunchyroll For Dubs in DE, PT, FR and ES)
   - English Translation for the Anime Names
   - ZORO Const Proxy (@K3NOXOFFICIAL) (@ahmedalashhab)
   - Project Update (@K3NOXOFFICIAL) (@ahmedalashhab)
  - #25 (@ahmedalashhab)

**Comment by ahmedalashhab** [comment]
These are great ideas. I'll look into adding them in time. Some of them have already been implemented but disabled due to the API facing difficulties. Like the button to skip the intro. Hopefully I can bring that back soon. Whenever you select an episode on a show, a continue watching row is created on the main page. Give it a go ;)

**Comment by K3NOXOFFICIAL** [comment]
@ahmedalashhab 
I see, hopefully the API facing difficulties will resolve soon. By API u mean Consumet cause maybe we can desolve those Problems ourselves.
Also i meant continue watching not only on a Episode base but a minute and seconds base so it stores the time where you left of.
Also if i want to contribute to the Code do I do it by opening a Pull request?

P.S. If i have more Ideas im just gonna update the List.

**Comment by ahmedalashhab** [comment]
Adding minutes and episodes should be a piece of cake actually :) I'd love to add that functionality soon. Would be super useful for movies especially. You are very welcome to make a PR and help build this app 😄

Also, feel free to join Ashanime's discord server for quicker comms if you wish.

**Comment by K3NOXOFFICIAL** [comment]
@ahmedalashhab 
As previously mentioned the discord invite is invalid and i can't join.
Please update and set it to Never Ending as seen here:
![image](https://user-images.githubusercontent.com/46091052/205376168-9a536c4e-525f-4faa-a050-6ec6e25355a3.png)

**Comment by ahmedalashhab** [comment]
Thanks! Here's the new link: https://discord.gg/G8W8wwEWfj

**Comment by K3NOXOFFICIAL** [comment]
@ahmedalashhab Thanks a lot

**Comment by TropicLegend** [comment]
Is it possible for you to add an option to self-host the database?

**Comment by K3NOXOFFICIAL** [comment]
> Is it possible for you to add an option to self-host the database?

I will look into the possibility of doing that, added to To-Do for now.
